baseURL = 'http://example.com/'
languageCode = 'zh-cn'
title = 'Trans Memories'
copyright = ""
googleAnalytics = ""
theme = "memory"

[outputs]
    home = ["HTML","RSS","JSON"]

[taxonomies]
tag = "tags"
category = "categories"
archive = "archives"

[params]
keyguard = ""
SEOTitle = "hi"
timeFormat = "Mon Jan 02 2006"
description = "Hi there ~"

[[params.social]]
type = "github"
name = "Github"
url = "https://github.com"
icon = "ri-github-fill"